services:
  clip-service:
    build:
      context: ./clip-service
      dockerfile: Dockerfile-hybrid
    ports:
      - "8001:8001"
    volumes:
      - ./clip-service/chroma_db:/app/chroma_db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLIP_SERVICE_URL=http://clip-service:8001
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - clip-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped